apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: topologyupdater-securitycontext.yaml
  target:
    labelSelector: app=nfd
    name: nfd-topology-updater
- path: topologyupdater-mounts.yaml
  target:
    labelSelector: app=nfd
    name: nfd-topology-updater
- path: sleep-interval-flag.yaml
  target:
    labelSelector: app=nfd
    name: nfd-topology-updater
- path: env.yaml
  target:
    labelSelector: app=nfd
    name: nfd-topology-updater
