apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- ../../base/rbac-topologyupdater
- ../../base/rbac-topology-gc
- ../../base/noderesourcetopologies-crd
- ../../base/topologyupdater-daemonset
- ../../base/topology-gc
- namespace.yaml

components:
- ../../components/common
- ../../components/topology-updater
- ../../components/topology-updater-config
