apiVersion: kustomize.config.k8s.io/v1alpha1
kind: Component

patches:
- path: env.yaml
  target:
    labelSelector: app=nfd
    name: nfd.*
- path: securitycontext.yaml
  target:
    labelSelector: app=nfd
    name: nfd.*
- path: master-affinity.yaml
  target:
    labelSelector: app=nfd
    name: nfd-master
- path: worker-mounts.yaml
  target:
    labelSelector: app=nfd
    name: nfd-worker
# We need separate patches for the "combined" daemonset with two containers in the pod :/
- path: env-combined.yaml
  target:
    labelSelector: app=nfd
    name: nfd
- path: securitycontext-combined.yaml
  target:
    labelSelector: app=nfd
    name: nfd
- path: master-affinity.yaml
  target:
    labelSelector: app=nfd
    name: nfd
- path: worker-mounts-combined.yaml
  target:
    labelSelector: app=nfd
    name: nfd
- path: master-mounts.yaml
  target:
    labelSelector: app=nfd
    name: nfd-master
