apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: node-feature-discovery

resources:
- ../../base/rbac
- namespace.yaml
- master-job.yaml

components:
- ../../components/common
- ../../components/master-config

patches:
- path: master-clusterrole.yaml
  target:
    kind: ClusterRole
    name: nfd-master
